FROM python:3.9-buster

ENV WORKDIR=/workspace
ENV PYTHONPATH=${PYTHONPATH}:${WORKDIR}
WORKDIR ${WORKDIR}

COPY src ${WORKDIR}/src
WORKDIR ${WORKDIR}/src/Services/celery
RUN apt update && apt install git
RUN pip install -r requirements-celery.txt

CMD celery -A app worker -B --loglevel=INFO -f /var/log/celery.log
ENTRYPOINT celery -A app worker -B --loglevel=INFO -f /var/log/celery.log
