"""add processor

Revision ID: 1e7fc02b4bcf
Revises: d067edaab3c1
Create Date: 2021-04-28 07:04:24.921916

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '1e7fc02b4bcf'
down_revision = 'd067edaab3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    processor = op.create_table('processor',
                                sa.Column('name', sa.Enum('DISCORD_HOOKER', 'GSC_NEW_ANNOUN_CRAWLER',
                                          name='processorid'), nullable=False),
                                sa.Column('type', sa.Enum('CRAWLER', 'SENDER', name='processortype'), nullable=False),
                                sa.Column('status', sa.Enum('SUCCESS', 'WARNING', 'FAILED',
                                          name='processorstatus'), nullable=True),
                                sa.Column('executed_at', sa.DateTime(), nullable=True),
                                sa.PrimaryKeyConstraint('name')
                                )
    op.bulk_insert(processor, [
        {"name": 'DISCORD_HOOKER', "type": "SENDER", "status": "SUCCESS", "executed_at": datetime.now()},
        {"name": 'GSC_NEW_ANNOUN_CRAWLER', "type": "CRAWLER", "status": "SUCCESS", "executed_at": datetime.now()}
    ])
    op.add_column('webhook', sa.Column('status_code', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook', 'status_code')
    op.drop_table('processor')
    op.execute('DROP TYPE processorid;')
    op.execute('DROP TYPE processortype;')
    op.execute('DROP TYPE processorstatus;')
    # ### end Alembic commands ###
