"""empty message

Revision ID: 27a7a6137e1f
Revises: e595be1e7783
Create Date: 2020-12-03 11:15:18.944745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a7a6137e1f'
down_revision = 'e595be1e7783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    # ### end Alembic commands ###
