"""empty message

Revision ID: 28889fdeb033
Revises: 16ee91ee3713
Create Date: 2021-03-17 15:20:59.876144

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '28889fdeb033'
down_revision = '16ee91ee3713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_checksum',
    sa.Column('site', sa.Enum('GSC', 'ALTER', name='sourcesite'), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('site')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_checksum')
    op.execute('DROP TYPE sourcesite;')
    # ### end Alembic commands ###
