"""add is_nsfw, lang in webhook

Revision ID: 297a88b4891f
Revises: 8feb052e1f89
Create Date: 2021-05-05 20:54:19.860988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297a88b4891f'
down_revision = '8feb052e1f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('is_nsfw', sa.Boolean(), nullable=True))
    op.add_column('webhook', sa.Column('lang', sa.String(length=5), nullable=True))
    op.execute("UPDATE webhook SET is_nsfw=true WHERE is_nsfw ISNULL;")
    op.execute("UPDATE webhook SET lang='en' WHERE lang ISNULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook', 'lang')
    op.drop_column('webhook', 'is_nsfw')
    # ### end Alembic commands ###
