"""Product jan BigInteger > String(13)

Revision ID: 3057c19a2f4f
Revises: e34abd051bfb
Create Date: 2021-04-16 23:13:47.058462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3057c19a2f4f'
down_revision = 'e34abd051bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'jan',
                    type_=sa.String(13),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'jan',
                    type_=sa.BigInteger(),
                    nullable=True)
    # ### end Alembic commands ###
