"""add thumbnail and og_image in product

Revision ID: 3bd094f697e8
Revises: 297a88b4891f
Create Date: 2021-05-14 23:50:54.391524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd094f697e8'
down_revision = '297a88b4891f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('product', sa.Column('og_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'og_image')
    op.drop_column('product', 'thumbnail')
    # ### end Alembic commands ###
