"""empty message

Revision ID: 548924d9d900
Revises: a35f8795768a
Create Date: 2020-12-04 12:09:03.659569

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '548924d9d900'
down_revision = 'a35f8795768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_release_info', 'initial_release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('product_release_info', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_release_info', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_release_info', 'initial_release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
