"""add tax_including column in pri

Revision ID: 74d27e0219cb
Revises: ef71eca5865e
Create Date: 2021-06-05 16:52:24.219763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d27e0219cb'
down_revision = 'ef71eca5865e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_release_info', sa.Column('tax_including', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_release_info', 'tax_including')
    # ### end Alembic commands ###
