"""removed processor

Revision ID: 76e28793186f
Revises: 9ad21de124d0
Create Date: 2021-04-30 13:01:36.280477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76e28793186f'
down_revision = '9ad21de124d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processor',
    sa.Column('name', postgresql.ENUM('DISCORD_HOOKER', 'GSC_NEW_ANNOUN_CRAWLER', name='processorid'), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('CRAWLER', 'SENDER', name='processortype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'WARNING', 'FAILED', name='processorstatus'), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='processor_pkey')
    )
    # ### end Alembic commands ###
