"""adjust webhook columns

Revision ID: 7b91272574de
Revises: 8c60edb390f3
Create Date: 2021-04-28 08:49:42.254610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b91272574de'
down_revision = '8c60edb390f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('webhook', sa.Column('token', sa.String(), nullable=True))
    op.drop_column('webhook', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('webhook', 'token')
    op.drop_column('webhook', 'id')
    # ### end Alembic commands ###
