"""fix column name

Revision ID: 8843334194e0
Revises: ab7e624a1170
Create Date: 2020-12-04 06:02:41.908037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8843334194e0'
down_revision = 'ab7e624a1170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_categroy_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.drop_column('product', 'categroy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categroy_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_categroy_id_fkey', 'product', 'category', ['categroy_id'], ['id'])
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
