"""add table task

Revision ID: 8feb052e1f89
Revises: 76e28793186f
Create Date: 2021-04-30 13:07:05.352935

"""
from datetime import datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8feb052e1f89'
down_revision = '76e28793186f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    task = op.create_table('periodic_task',
                           sa.Column('name', sa.Enum('NEWS_PUSH', name='periodictask'), nullable=False),
                           sa.Column('executed_at', sa.DateTime(), nullable=True),
                           sa.PrimaryKeyConstraint('name')
                           )

    op.bulk_insert(task, [
        {"name": 'NEWS_PUSH',  "executed_at": datetime.now()},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodic_task')
    # ### end Alembic commands ###
