"""alter column webhook.is_successed -> is_existed

Revision ID: 9ad21de124d0
Revises: 275d36156c6d
Create Date: 2021-04-29 08:28:05.630568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad21de124d0'
down_revision = '275d36156c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('is_existed', sa.Boolean(), nullable=True))
    op.drop_column('webhook', 'is_successed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('is_successed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('webhook', 'is_existed')
    # ### end Alembic commands ###
