"""webhook id is too large should use string

Revision ID: a7471913196e
Revises: 7b91272574de
Create Date: 2021-04-28 12:49:56.904128

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a7471913196e'
down_revision = '7b91272574de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("webhook", "id", type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("webhook", "id", type_=sa.Integer())
    # ### end Alembic commands ###
