"""add_timestamp_related column in ProductReleaseInfo


Revision ID: bab26a6e0ae2
Revises: 3057c19a2f4f
Create Date: 2021-04-22 05:45:14.676499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab26a6e0ae2'
down_revision = '3057c19a2f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_release_info', sa.Column('created_at', sa.TIMESTAMP(),
                  server_default=sa.func.current_timestamp(), nullable=False))
    op.add_column('product_release_info', sa.Column('updated_at', sa.TIMESTAMP(),
                  server_default=sa.func.current_timestamp(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_release_info', 'updated_at')
    op.drop_column('product_release_info', 'created_at')
    # ### end Alembic commands ###
