"""empty message

Revision ID: bf72540c22df
Revises: 27a7a6137e1f
Create Date: 2020-12-03 13:30:09.513092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf72540c22df'
down_revision = '27a7a6137e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_maker_id_key', 'product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_maker_id_key', 'product', ['maker_id'])
    # ### end Alembic commands ###
