"""add checked_at in announcement_checksum

Revision ID: d3fe6af29400
Revises: 28889fdeb033
Create Date: 2021-03-18 19:23:20.673031

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd3fe6af29400'
down_revision = '28889fdeb033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement_checksum', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement_checksum', 'checked_at')
    # ### end Alembic commands ###
