"""add order column in ProductOfficialImage

Revision ID: dba10aed3a40
Revises: d3fe6af29400
Create Date: 2021-04-03 18:55:14.048183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba10aed3a40'
down_revision = 'd3fe6af29400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_official_image', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_official_image', 'order')
    # ### end Alembic commands ###
