"""move order_period columns to product

Revision ID: e34abd051bfb
Revises: f3b78e6906a4
Create Date: 2021-04-12 17:44:40.224573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e34abd051bfb'
down_revision = 'f3b78e6906a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('order_period_end', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('order_period_start', sa.DateTime(), nullable=True))
    op.drop_constraint('product_official_image_product_id_fkey', 'product_official_image', type_='foreignkey')
    op.create_foreign_key(None, 'product_official_image', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_release_info_product_id_fkey', 'product_release_info', type_='foreignkey')
    op.create_foreign_key(None, 'product_release_info', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_release_info', 'order_period_end')
    op.drop_column('product_release_info', 'order_period_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_release_info', sa.Column('order_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('product_release_info', sa.Column('order_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_release_info', type_='foreignkey')
    op.create_foreign_key('product_release_info_product_id_fkey', 'product_release_info', 'product', ['product_id'], ['id'])
    op.drop_constraint(None, 'product_official_image', type_='foreignkey')
    op.create_foreign_key('product_official_image_product_id_fkey', 'product_official_image', 'product', ['product_id'], ['id'])
    op.drop_column('product', 'order_period_start')
    op.drop_column('product', 'order_period_end')
    # ### end Alembic commands ###
