"""webhook id is unique

Revision ID: ec698af7e1d7
Revises: f345a68553b9
Create Date: 2021-04-28 15:25:26.854791

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ec698af7e1d7'
down_revision = 'f345a68553b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'webhook', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook', type_='unique')
    # ### end Alembic commands ###
