"""product_release_info release_at -> shipped_at

Revision ID: ef71eca5865e
Revises: 005ff8428793
Create Date: 2021-05-26 15:00:59.081093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef71eca5865e'
down_revision = '005ff8428793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_release_info', sa.Column('shipped_at', sa.Date(), nullable=True))
    op.drop_column('product_release_info', 'release_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_release_info', sa.Column('release_at', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('product_release_info', 'shipped_at')
    # ### end Alembic commands ###
