"""webhook with timestamp and status column

Revision ID: f345a68553b9
Revises: a7471913196e
Create Date: 2021-04-28 13:11:51.924568

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f345a68553b9'
down_revision = 'a7471913196e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('webhook', sa.Column('is_successed', sa.Boolean(), nullable=True))
    op.add_column('webhook', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('webhook', 'status_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('status_code', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('webhook', 'updated_at')
    op.drop_column('webhook', 'is_successed')
    op.drop_column('webhook', 'created_at')
    # ### end Alembic commands ###
