"""add checksum column in product

Revision ID: f3b78e6906a4
Revises: dba10aed3a40
Create Date: 2021-04-07 13:18:07.832608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b78e6906a4'
down_revision = 'dba10aed3a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('checksum', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'checksum')
    # ### end Alembic commands ###
