"""product.orderperiod with timezone

Revision ID: fb10e089a8c0
Revises: 1e7fc02b4bcf
Create Date: 2021-04-28 07:53:51.833944

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fb10e089a8c0'
down_revision = '1e7fc02b4bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "order_period_start", type_=sa.DateTime(timezone=True))
    op.alter_column("product", "order_period_end", type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "order_period_start", type_=sa.DateTime())
    op.alter_column("product", "order_period_end", type_=sa.DateTime())
    # ### end Alembic commands ###
